# frozen_string_literal: true

require "bundler/gem_tasks"
require "defra_ruby_template/version"

DIST = "node_modules/govuk-frontend/dist/govuk"

# Everything under these paths is generated by the tasks below, so it is wiped
# first. Without this, files that govuk-frontend has since removed (v5's
# all.scss, the pre-v5 crest PNGs, the v5 rebrand/ asset directory) survive
# forever and the vendored copy drifts away from the release it claims to be.
GENERATED_PATHS = %w[
  vendor/assets/assets
  vendor/assets/fonts
  vendor/assets/images
  vendor/assets/javascripts/defra_ruby_template.js
  vendor/assets/javascripts/defra_ruby_template_supported.js
  vendor/assets/stylesheets
].freeze

task default: :assets

desc "Vendor every govuk-frontend asset the gem ships"
task "assets" do
  %w[
    clean
    minified_css
    fonts
    images
    manifest
    stylesheets
    javascripts
  ].each do |task_name|
    Rake::Task[task_name].execute
  end
end

def copy_assets(source_pattern, target_replacement)
  Rake::FileList[source_pattern].each do |source|
    target = source.sub(DIST, target_replacement)
    ensure_directory_for(target)
    copy_file source, target
  end
end

# govuk-frontend ships hundreds of files across a handful of directories, and an
# unconditional mkdir_p logs a line for every one of them.
def ensure_directory_for(target)
  directory = File.dirname(target)
  mkdir_p(directory) unless File.directory?(directory)
end

desc "Remove the vendored assets so no file outlives the release that shipped it"
task "clean" do
  GENERATED_PATHS.each { |path| rm_rf(path) }
end

desc "Vendor the prebuilt govuk-frontend stylesheet"
task "minified_css" do
  copy_assets("#{DIST}/govuk-frontend.min.css", "vendor/assets/stylesheets")
end

desc "Vendor the govuk-frontend Sass and write the gem stylesheet entry point"
task "stylesheets" do
  copy_assets("#{DIST}/**/*.scss", "vendor/assets/stylesheets")
  create_scss_file
end

# Fonts and images are vendored twice, under two different Sprockets load paths:
#
#   vendor/assets/{fonts,images}  -> logical paths "light-....woff2", "favicon.ico"
#   vendor/assets/assets/*        -> logical paths "fonts/light-....woff2", "images/favicon.ico"
#
# The first is what font-url()/image-url() and the layout's asset_path resolve
# against. The second backs govuk-frontend's own default $govuk-assets-path of
# "/assets/", which manifest.json's relative icon paths also rely on.
desc "Vendor the GDS Transport fonts"
task "fonts" do
  copy_assets("#{DIST}/assets/fonts/*.{eot,woff,woff2,ico,svg}", "vendor")
  copy_assets("#{DIST}/assets/fonts/*.{eot,woff,woff2,ico,svg}", "vendor/assets")
end

desc "Vendor the GOV.UK icons and images"
task "images" do
  copy_assets("#{DIST}/assets/images/*.{png,gif,jpg,ico,svg}", "vendor")
  copy_assets("#{DIST}/assets/images/*.{png,gif,jpg,ico,svg}", "vendor/assets")
end

# govuk-frontend 6's template links a web app manifest, and the manifest points
# at its icons with paths relative to itself ("images/favicon.ico"). Sprockets
# serves digested filenames in production, so those relative paths would 404.
# Vendor it as an ERB template instead and let Sprockets resolve each icon.
desc "Vendor the web app manifest as an asset pipeline template"
task "manifest" do
  source = "#{DIST}/assets/manifest.json"
  target = "vendor/assets/assets/manifest.json.erb"

  content = File.read(source).gsub(%r{"src": "images/([^"]+)"}) do
    %("src": "<%= asset_path "#{Regexp.last_match(1)}" %>")
  end

  raise "No icon paths were rewritten in #{source}" unless content.include?("asset_path")

  ensure_directory_for(target)
  File.write(target, content)
end

desc "Vendor the govuk-frontend bundle and the govuk-frontend-supported snippet"
task "javascripts" do
  Rake::FileList["#{DIST}/all.bundle.js"].each do |source|
    target = source.sub(DIST, "vendor/assets/javascripts")
    target = target.sub("all.bundle.js", "defra_ruby_template.js")
    ensure_directory_for(target)
    copy_file source, target
  end

  create_supported_js_file
end

# govuk-frontend's own entry point (index.scss) is a Sass module: it uses
# @use/@forward and ships sibling *.import.scss shims for @import callers. Both
# need Dart Sass - LibSass does not implement the module system and quietly
# emits the @use rules as literal CSS, producing a stylesheet with no styles in
# it. Consuming apps import this file, so all it does is point the asset URL
# helpers at Sprockets (when Sprockets is what is compiling it) and hand over to
# govuk-frontend.
#
# It deliberately no longer wraps govuk-frontend's all.scss, which exists only
# to emit an "Importing using 'govuk/all' is deprecated" warning on every
# compile.
SCSS_ENTRY_POINT = <<~SCSS
  // Compiled through Sprockets (sassc-rails, dartsass-sprockets) the Rails
  // asset helpers are registered as Sass functions, so hand govuk-frontend
  // their names and asset URLs resolve to digest paths. Compiled standalone
  // (dartsass-rails, a plain `sass` run) they do not exist, and govuk-frontend
  // falls back to $govuk-images-path / $govuk-fonts-path.
  //
  // The variables are declared before the @if so that the assignment inside it
  // updates the global rather than creating one scoped to the @if.
  @use "sass:meta";

  $govuk-image-url-function: null;
  $govuk-font-url-function: null;

  @if meta.function-exists("image-url") {
    $govuk-image-url-function: "image-url";
  }

  @if meta.function-exists("font-url") {
    $govuk-font-url-function: "font-url";
  }

  // Passing the helpers by name is the only form available to @import users,
  // and govuk-frontend deprecates it in favour of meta.get-function, which
  // needs @use. Silence the warning until this file can be migrated.
  $govuk-suppressed-warnings: ("image-url-string", "font-url-string");

  // index.import rather than index: Dart Sass maps `@import "index"` onto
  // index.import.scss itself, but Sprockets-based pipelines supply their own
  // importer and resolve `index` to index.scss - the module entry point, which
  // silently ignores the settings above and emits undigested asset URLs.
  // Naming the shim explicitly makes both routes behave the same.
  @import "index.import";
SCSS

def create_scss_file
  target_file = "vendor/assets/stylesheets/defra_ruby_template.scss"

  ensure_directory_for(target_file)
  File.write(target_file, SCSS_ENTRY_POINT)
end

# govuk-frontend gates 100+ CSS rule blocks and every component's JavaScript on
# the govuk-frontend-supported class, and initAll() raises SupportError without
# it. Upstream sets it from an inline script in template.njk, which a strict
# script-src CSP blocks, so extract that one statement into an asset the layout
# can include instead. Extracting rather than hardcoding keeps it honest if
# upstream ever changes the statement.
def create_supported_js_file
  template = File.read("#{DIST}/template.njk")
  snippet = template[%r{<script[^>]*>(document\.body\.className \+=.*?)</script>}m, 1]

  raise "Could not find the js-enabled snippet in #{DIST}/template.njk" if snippet.nil?

  target_file = "vendor/assets/javascripts/defra_ruby_template_supported.js"

  ensure_directory_for(target_file)
  File.write(target_file, <<~JS)
    // Extracted from govuk-frontend's template.njk, where it is an inline
    // <script> that a strict script-src Content-Security-Policy blocks.
    // Generated by `rake javascripts` - do not edit by hand.
    #{snippet.strip}
  JS
end
